### ISSUE TITLE
Eos Issue Tracking

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/pyfa-ng#3]
This should really be under the Eos repo, but _someone_ didn't enable issues there. :)
(We can move this if/when it is.)

Some features that Eos seems to be missing (some may just need to be confirmed).
- [ ] T3D Modes (This is just a module in game, can we do something similar?)
- [ ] T3C Subsystems
- [ ] Citadels (can we just treat this as ships?)
- [ ] Citadel modules (currently none that I know of that would modify fitting stats)
- [ ] Projection (Ships and fits)

Potential Bugs/Issues with Eos:
- Need to confirm, but seems Eos only returns an except for each error if the error is the same type.  Ideally it returns an exception with all issues with the fit.

**Comment by Ebag333** [comment]
Moved to https://github.com/pyfa-org/eos/issues/6 where it belongs.
